### ISSUE TITLE
Add game Towers

### ISSUE THREAD

**Issue by krawaller** [krawaller/algol5#357]
Paco Barter has given us permission to add the super simple game he described in this BGG thread about suitable abstracts for 5 year olds.

![image](https://user-images.githubusercontent.com/249764/93415079-f78fac80-f8a2-11ea-9407-56e569a98e64.png)

In the geekmail reply where he gives permission he said he called the game "Towers".

We should probably add a variant where you have to move out of your base first, to prevent cheesing.

https://boardgamegeek.com/thread/2460837/article/35287297#35287297

**Comment by krawaller** [comment]
@wnr If you're still having fun and weren't scared off by #362, this is another game that should be very easy to add! It has sliding just like Neutreeko, and the winning by moving all units into an area you can steal from Tobito (the `invasion` win condition).

**Comment by wnr** [comment]
@krawaller Cool! I'm on it
