### ISSUE TITLE
Add game Jeson Mor

### ISSUE THREAD

**Issue by krawaller** [krawaller/algol5#369]
Pretty easy implementation:

![image](https://user-images.githubusercontent.com/249764/94894742-44ba7380-048a-11eb-81aa-780a92ec178e.png)

* Units move like chess knight (see Chameleon for how to do that)
* Win by moving _out of_ the central square! This means that if the opponent has a unit there we should be forced to kill it. In other words, if we have an enemy in the central square, don't give move options anywhere else.

http://www.di.fc.ul.pt/~jpn/gv/jesonmor.htm
http://www.zillions-of-games.com/cgi-bin/zilligames/submissions.cgi?do=show;id=503
https://boardgamegeek.com/boardgame/37917/jeson-mor

**Comment by wnr** [comment]
See #369
