### ISSUE TITLE
Add Outwit

### ISSUE THREAD

**Issue by krawaller** [krawaller/algol5#413]
![image](https://user-images.githubusercontent.com/249764/101878267-915bb280-3b8f-11eb-9121-61d343eac33a.png)
![image](https://user-images.githubusercontent.com/249764/102006262-f514e580-3d1f-11eb-9c63-c9ef6948d7a5.png)

Rules

* There are two unit types:
    * soldiers move like chess rooks except they must always move as far as possible
    * kings move like chess queens
* There are no captures
* Once a piece enters your base it may never move again

Links

* https://boardgamegeek.com/boardgame/4696/outwit
* http://www.di.fc.ul.pt/~jpn/gv/outwit.htm

Implementation notes

* Chessicals doesn't work well with portrait shaped boards, so we'll need to rotate this into a 10x9 instead of a 9x10!
* For sliding moves, see any game with the [Slide](https://chessicals.com/tags/slide/) tag
* For not being able to move a piece after it has entered the base, see [Can the Sardines](https://chessicals.com/games/can_the_sardines/)

**Comment by joelfransson** [comment]
I'll start working on this one 👍
