### ISSUE TITLE
Add Grensholm

### ISSUE THREAD

**Issue by krawaller** [krawaller/algol5#414]
![image](https://user-images.githubusercontent.com/249764/101879245-5195ca80-3b91-11eb-8f8d-6625dea048bf.png)

Rules:

* Soldiers move like knights in chess, except you must move towards the opponent's side
* Once a soldier reach the opponent side they are promoted to a "king", which still moves like a knight but must now move back home
* Winner is first to get a king back home
* Both soldiers and kings capture by replacement

Links: 

* http://www.di.fc.ul.pt/~jpn/gv/grensholm.htm
* https://www.zillions-of-games.com/cgi-bin/zilligames/submissions.cgi/49215?do=show;id=1009
* http://blog.krawaller.se/algol4/#/game/grensholm/info

Implementation notes:

* The rules of Grensholm are super similar to [Ugly Duck](https://chessicals.com/games/ugly_duck/), so check out the definition of that game for lots of help!
* The UI in Chessicals doesn't work well with "portrait" rectangles, so we should rotate the board 90 degrees (so that it is 6x4 instead of 4x6)
* To make "chess horse movement" available we must add an offset definition to the board. This will generate all "horse links" between squares initially, so we don't have to calculate them during play. See for example [Chameleon](https://chessicals.com/games/chameleon/) to see how this is done
* To make a piece able to move like a chess horse, you would normally just use `dirs: "knight"`. But here we just want to make SOME of those dirs available (those who move us towards the opponent base, or back if we're a king). If you look in the file `modules/common/connections/dirConstants.ts`, you'll see that `"knight"` is just a shortcut for a range of offset dirs, just like `"ortho"` is a shortcut for `[1, 3, 5, 7]`. So you need to hand-pick the correct offsets from that list, depending on if we're a soldier or king, and if we're player 1 or 2.

Suggested iteration:

* Flow of the game would be sth like: `selectunit -> selectmovetarget -> move`, with a single generator `findmovetargets` triggered by `selectunit`.
* Start by just making the soldiers move like regular chess horsers (`dirs: "knight"`), and capture by replacement (use `stomp` for movement effect).
* Next add promotion to king if we end our move in opponent base
* Next make it so that soldiers have to move towards opp base and kings must move homewards
* Next add win condition for having a king in the own base! Pro tip: to test this, make a temporary change to the setup where you place a king within reach of the home row, that way you don't have to play through an almost full game just to see if it works!

**Comment by wnr** [comment]
I'll do this one :)
